### ISSUE TITLE
Cannot override iron-dropdown styles

### ISSUE THREAD

**Issue by cassiechin** [PolymerElements/iron-dropdown#103]
### Description
Cannot override iron-dropdown styles; to be specific, component authors of the component currently cannot override iron-dropdown distributed children slotted into its `#contentWrapper`.

### Expected outcome

Being able to override its properties such as `overflow: auto` & `position:fixed` to accommodate particular elements that these styles become problematic to work around. 

For example, wanted the paper-items to fully expand in contexts and never collapsed to a fixed, scrollable size.
### Actual outcome
Cannot override `overflow: auto` and `position:fixed` and having to resort to deprecated `/deep/` or consider recreating this component without such limitations.

### Live Demo
Can't provide a demo, the code is associated with a closed-source Google project; feel free to DM you more context. 

### Steps to reproduce
1. Attempt to use `paper-button-menu`/`paper-menu` that has `iron-dropdown`  as a hard dependency
2. Attempt to style a dropdown that needs to be fully expanded regardless of where the user is on the page and have a effect that the container of the dropdown items don't move
3. Without the ability to override the the styles applied by all content within `#contentWrapper`, the container of the the dropdown will collapse with a vertical scrollbar that can't be overridden

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by valdrinkoshi** [comment]
The sizing & positioning is handled by `iron-fit-behavior`, which will ensure to respect `fitInto` & keep the element within its boundaries, and use `positionTarget + verticalAlign + horizontalAlign` for the positioning. I'd suggest to set the `fitInto` to the scrollable area, so that you won't have any scrollbar.
`iron-fit-behavior` has currently an issue where the offset of the `fitInto` is not taken in consideration: that's being fixed in https://github.com/PolymerElements/iron-fit-behavior/pull/59
Here's an example of this working with a `paper-menu-button` and the patched fix for `iron-fit-behavior`: all you need to do is set the dropdown's `fitInto` to the scrolling element (in the example `document.body`) http://jsbin.com/rujuze/4/edit?html,output

Exposing mixins to the element user might be dangerous as it would be very easy to break the positioning/sizing calculations and possibly have buggy animations.
