### ISSUE TITLE
find scrollable parent instead of defaulting to document.body

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-dropdown#107]
Currently the `iron-dropdown` will assume only body is scrollable. But if scroll happens in another scrollable parent the flow is broken, e.g. `iron-dropdown` that allows outside scrolls doesn't get its position updated http://jsbin.com/jucoda/2/edit?html,output

**Comment by danbeam** [comment]
thanks for this issue, @valdrinkoshi!

**Comment by danbeam** [comment]
@tjsavage

**Comment by randyaskin** [comment]
I know this issue is a bit stale, but did anyone look into this or come up with a workaround? Several of our components that use iron-dropdown are having this issue where the dropdown and its trigger get out of sync on scroll. One of my colleagues experimented with crawling the DOM to find all scrollable parents and update position on scroll, but we weren't sure that was a very efficient or performant solution. TIA!

**Comment by valdrinkoshi** [comment]
I think this issue should be moved to iron-overlay-behavior as now the scroll handling is done there.

Seems like `scroll` events can be captured (via an event listener with useCapture = true), but cannot get events happening inside shadowRoots (when using native ShadowDOM).
E.g. try this, see how we don't receive events when we scroll the element `scroll_0-1__shadow-scrollable` http://jsbin.com/qinekat/4/edit?html,output

That would require walking up the parents to search for shadowRoots rather than scrollable nodes, which is less expensive. 
Will take a stab at that 👍

**Comment by benoitjchevalier** [comment]
Awesome, sounds like a good solution 👍 . Do you want us to open another issue on iron-overlay-behavior?

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#254
