### ISSUE TITLE
why allway set body to overflow: hidden;

### ISSUE THREAD

**Issue by hzmnet** [PolymerElements/iron-dropdown#135]
the scroll always hidden and show when the menu open and close. because the iron-dropdown-scroll-manager.html  set the body to overflow: hidden;

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
We choose to not set the `overflow: hidden` to `<body>` because otherwise that would change its width on windows (because the scrollbar will be hidden). This was filed in #81 and we fixed it.

Similar to #139, see more details here https://github.com/PolymerElements/iron-dropdown/issues/139#issuecomment-377464950
