### ISSUE TITLE
Jerky scrolling behavior on Firefox and mobile devices

### ISSUE THREAD

**Issue by lpellegr** [PolymerElements/iron-dropdown#152]
When `allowOutsideScroll` is `true` and you tap on the element to display its `dropdown-content` and then scroll, the `dropdown-content` take a few milliseconds to realign, thus making the movement jerky. 

I am able to reproduce the issue with `iron-dropdown` version 2.2.0 on Firefox but also Chrome on Android. That's really annoying, especially if the drop-down is kept open on a page for demo purposes. The behavior is too jerky.

The `iron-dropdown` [demo page](https://www.webcomponents.org/element/PolymerElements/iron-dropdown/demo/demo/index.html) is a good place to reproduce the issue. Open it, move to "Scroll actions" example and click on "Refit on scroll" button. Then, scroll down and up several times.

Another example in a landing page:

https://noticeable.io

Look at the widget in the center when you scroll down and up.

This issue seems there since months. Any workarounds or ideas about the cause of this jerky movement on scrolling?

**Comment by lpellegr** [comment]
The following patch fixes the scrolling issue but breaks the positioning:

https://github.com/childdotorg/iron-dropdown/commit/eba9a58caa733dbc0b2e36a456917dd1d2b4f209

At first sight, the issue seems due to the fixed position of the host element.

**Comment by lpellegr** [comment]
@valdrinkoshi  Any thoughts?

**Comment by valdrinkoshi** [comment]
The reason why is janky is because `iron-dropdown` is `position: fixed` and recomputes the position where it should be at each frame through a `raf`.
It is `position: fixed` because its `positionTarget` might be different from the `offsetParent`, and as a consequence we need to listen for scroll events and update positioning - scroll events are received after the fact happened, and on top of that we "deRAF" the position update (aka we do requestAnimationFrame(refit)`.

One possible improvement we could try is set `position: absolute` if `positionTarget === offsetParent` (to be done in `iron-fit-behavior`), which handles cases like this:
```html
<style>
  .container { position: relative; }
</style>
<div class="container">
  <iron-dropdown allow-outside-scroll>
```
Would you be willing to give it a try? PR welcome!

A solution that works with current implementation is unset vertical/horizontal-align and `position: absolute` on the dropdown:
```html
<style>
  .container { position: relative; }
  .container iron-dropdown {
    position: absolute;
    left: 0; /* vertical-align="left" */
    top: 0; /* vertical-align="top" */
  }
</style>
<div class="container">
  <iron-dropdown allow-outside-scroll horizontal-align="" vertical-align="">
```

**Comment by valdrinkoshi** [comment]
In terms of UX, `<iron-dropdown>` was conceived to behave as the native `<select>`: it either locks scrolling outside or closes on scroll outside (both supported through the [`scrollAction` property](https://www.webcomponents.org/element/PolymerElements/iron-dropdown/elements/iron-dropdown#property-scrollAction). 
`allowOutsideScroll` is something in between, for which one would be better off simply using `position: absolute` and do the actual positioning themselves:
```html
<div style="position:relative">
  <simple-overlay style="position: absolute; top: 0; left: 0">
```

**Comment by lpellegr** [comment]
@valdrinkoshi Thanks a lot for your explanations. I was able to understand and fix the behavior. If I have the time, I will look for the PR you have suggested.
