### ISSUE TITLE
Why does it hide/show the main browser scrollbar?

### ISSUE THREAD

**Issue by JustinCase1089** [PolymerElements/iron-dropdown#31]
Hi 
I am experiencing a rather annoying issue. Whenever the drop down is invoked, the scrollbar of the web browser is hidden (to start with its there as the page is rather long) and appears again when a selection is made. This gives the page a temporary offset which doesn't look that nice. I am using Chrome for my test. How do I prevent the drop down menu from medding with the scrollbar?
Thanks :-)
Cheers
J

**Comment by notwaldorf** [comment]
`iron-dropdown` has an `allow-outside-scroll` attribute, that when set to `true` will stop disabling main document scrolling. Does that work for you?

**Comment by JustinCase1089** [comment]
Ah, I like that. Works beautifully. Thanks :-)

**Comment by govis** [comment]
On a related note - is there a way to have it try to expand and use available scroll space when <code>allow-outside-scroll</code> is <code>true</code> instead of being squeezed by the window bounds?

![image](https://cloud.githubusercontent.com/assets/971651/10545165/50205508-73f5-11e5-94da-60eb561cfc41.png)

**Comment by cdata** [comment]
@govis Yes, if you call `notifyResize` on the dropdown, or fire an `iron-resize` event on it or one of it's descendants.
