### ISSUE TITLE
Calling center() throws exception

### ISSUE THREAD

**Issue by StokeMasterJack** [PolymerElements/iron-dropdown#77]
this.$.dropdown.center();
Causes this exception:
iron-fit-behavior.html:242 Uncaught TypeError: Cannot read property 'positionedBy' of undefined

Here is a screenshot of the stacktrace:
![004](https://cloud.githubusercontent.com/assets/123349/14898256/b7b27e24-0d3a-11e6-9ccc-bf1ac5eda262.png)

I am on Chrome Version 50.0.2661.86 (64-bit)
Mac OS X Version 10.11.4 (15E65)

I was using Polymer 1.2 tried updating to Polymer/polymer#^1.4.0". Still same problem.

**Comment by StokeMasterJack** [comment]
I am using PolymerElements/iron-dropdown#~1.3.0

**Comment by valdrinkoshi** [comment]
Hi @StokeMasterJack, could you provide a jsbin exposing the issue? I cannot reproduce it http://jsbin.com/capuvu/1/edit?html,console,output

**Comment by StokeMasterJack** [comment]
I am not sure how to do jsbin when there are imported html files. I have trimmed the example down to the bare minimum of two html files. I have a attached a zip file containing the two html files plus the bower_components folder. The two html files are inside the components/tmp-picker folder.

[bug-demo.zip](https://github.com/PolymerElements/iron-dropdown/files/352560/bug-demo.zip)

**Comment by valdrinkoshi** [comment]
I see you're using `paper-dialog` and not `iron-dropdown`, so this is the wrong repo where to report it :)
You don't need to call `center()` right after `open()`, because `iron-overlay-behavior` will call it when is the right moment http://jsbin.com/capuvu/2/edit?html,console,output
Anyways, this seems to be a bug on `iron-fit-behavior` which crashes if you call `center()` for the first time: http://jsbin.com/juzaboz/1/edit?html,console,output

Will move the issue there

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-fit-behavior#57
